apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j08hqoj2d-python 
  janus-idp.io/tekton: j08hqoj2d-python
  backstage.io/kubernetes-id: j08hqoj2d-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j08hqoj2d-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml